version: 1
formatters:
  livres_formatter:
    format: "%(asctime)s-%(module)s-%(funcName)s-%(levelname)s-%(message)s"
    datefmt: "(%d/%Y-%I:%M)"
  transaction_formatter:
    format: "%(name)s-%(levelname)s-%(message)s"
filters:
  sensitive_info:
    (): __main__.SensitiveInfoFilter

handlers:
  transactions_stream_handler:
    class: logging.StreamHandler
    formatter: transaction_formatter
    stream: ext://sys.stdout
  livres_stream_handler:
    class: logging.StreamHandler
    formatter: livres_formatter
    stream: ext://sys.stdout

loggers:
  transactions_logger:
    level: ${LEVEL}
    handlers: [transactions_stream_handler]
  livres_logger:
    level: ${LEVEL}
    handlers: [livres_stream_handler]


